### PR TITLE
info

### PR DESCRIPTION
**Pull request by prateekazam**
2-Added info testcase

### CODE REVIEW

**Comment by prateekazam** [comment]
closing this because of conflict

**Review by laszewsk — COMMENTED** [review]
i do not see your changes reflected
did you merge or just close?

**Comment by laszewsk** [comment]
work only on info, make pull request on small thinsg ;-)

**Comment by prateekazam** [comment]
Reopening it

**Comment by laszewsk** [comment]
ok i look at this now ....

**Comment by laszewsk** [comment]
please test it out after i merged

**Comment by laszewsk** [comment]
this is now merged

**Comment by prateekazam** [comment]
Thank you, Professor.

**Comment by laszewsk** [comment]
make sure to work on test

**Pull request merged**
